backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "stories"
    label: "Story"
    folder: "src/content/stories"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "story"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "ID"
        name: "id"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - { label: "Body", name: "body", widget: "markdown" }
