backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "stories"
    label: "Story"
    folder: "src/content/stories"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "story"
        preview: false
      - label: "Title"
        name: "title"
        widget: "string"
        preview: false
      - label: "ID"
        name: "id"
        widget: "string"
        preview: false
      - label: "Description"
        name: "description"
        widget: "string"
        preview: false
      - label: "Date"
        name: "date"
        widget: "datetime"
        preview: false
      - label: "Body"
        name: "body"
        widget: "pages"
